### PR TITLE
Removed the underscore in the starting of the prefix

### PR DESCRIPTION
**Pull request by apicgg**

### CODE REVIEW

**Comment by apicgg** [comment]
@webbushka Is this one being maintained?

**Comment by webbushka** [comment]
Yes lightly maintained 😀. I can merge and publish this tomorrow. 

No concerns about name clashing on any of the imports? Specifically the empty import? Wonder if we are removing the `_` if we should change it to `im` instead

**Comment by apicgg** [comment]
> Yes lightly maintained 😀. I can merge and publish this tomorrow.
> 
> No concerns about name clashing on any of the imports? Specifically the empty import? Wonder if we are removing the `_` if we should change it to `im` instead

Totally agree with you about the empty imports. Thanks

**Comment by apicgg** [comment]
@webbushka Is this looks good to publish now?

**Review by webbushka — APPROVED** [review]

**Pull request merged**
